seed: 42

events_meta:
  evk_vnv_channel_group:
    cardinality: 10
    type: categorical
    event_id: 2
  evk_vnv_evt_attr_1:
    cardinality: 3
    type: categorical
    event_id: 2
  evk_vnv_sale_product_class_id:
    cardinality: 38
    type: categorical
    event_id: 2
  evk_vnv_sale_type_id:
    cardinality: 22
    type: categorical
    event_id: 2
  holidays_evt_attr_1:
    cardinality: 87
    type: categorical
    event_id: null
  pos_geo_evt_attr_1:
    cardinality: 87
    type: categorical
    event_id: null
  txn_evt_attr_4:
    cardinality: 3
    type: categorical
    event_id: [0, 1]
  txn_evt_attr_5:
    cardinality: 3
    type: categorical
    event_id: [0, 1]
  txn_evt_attr_15:
    cardinality: 1
    type: numerical
    event_id: [0, 1]
  txn_evt_attr_9:
    cardinality: 684
    type: categorical
    event_id: [0, 1]
  txn_evt_attr_1:
    cardinality: 429
    type: categorical
    event_id: 1
  txn_evt_attr_2:
    cardinality: 4
    type: categorical
    event_id: 1
  txn_evt_attr_3:
    cardinality: 44
    type: categorical
    event_id: 1

model:
  _target_: fmlib.nn.models.SequenceRepresentationModel
  embedding:
    _target_: fmlib.nn.embedding.EventEmbedding
    embedding_dim: 256
    columns_meta: ${events_meta}
  time_embedding:
    _target_: fmlib.nn.embedding.LinearEmbedding
    embedding_dim: ${model.embedding.embedding_dim}
    feature_count: 1
  feature_encoder_block:
    _target_: fmlib.nn.blocks.EventEncoderBlock
    hidden_dim: ${model.embedding.embedding_dim}
    attn_dropout: 0.0
    dropout: 0.1
    ffn:
      _target_: fmlib.nn.blocks.FeatureFFN
      model_dim: ${model.embedding.embedding_dim}
      linear_dim: 1024 # ${model.embedding.embedding_dim} * 4
      feature_dim: 14 # количество признаков + 1 (если есть time_embedding)
      dropout: ${model.feature_encoder_block.dropout}
  transformer_model:
    _target_: transformers.GPT2Model
    config:
      _target_: transformers.GPT2Config
      n_positions: 1024
      vocab_size: 0 # может быть любое значение, так как nn.Embedding gpt мы не используем
      n_embd: ${model.embedding.embedding_dim}
      n_layer: 8
      n_head: 4
      pad_token_id: 0
      bos_token_id: 1
      eos_token_id: 2
  aggregation_layer:
    _target_: fmlib.nn.utils.agg.Sum
  event_names:
    - "evk_vnv_channel_group"
    - "evk_vnv_evt_attr_1"
    - "evk_vnv_sale_product_class_id"
    - "evk_vnv_sale_type_id"
    - "holidays_evt_attr_1"
    - "pos_geo_evt_attr_1"
    - "txn_evt_attr_4"
    - "txn_evt_attr_5"
    - "txn_evt_attr_15"
    - "txn_evt_attr_9"
    - "txn_evt_attr_1"
    - "txn_evt_attr_2"
    - "txn_evt_attr_3"
  output_names:
    - "logits"
    - "last_hidden_state"

training_step_callbacks:
  _target_: fmlib.training.callbacks.step.GroupedStepCallback
  callbacks: []

validation_step_callbacks:
  _target_: fmlib.training.callbacks.step.GroupedStepCallback
  callbacks: []

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001

scheduler:
  _target_: transformers.optimization.get_scheduler
  name: cosine
  num_warmup_steps: 1
  num_training_steps: 300

accelerator:
  _target_: accelerate.Accelerator
  kwargs_handlers:
    - _target_: accelerate.utils.DistributedDataParallelKwargs
      find_unused_parameters: True

training_transform:
  _target_: fmlib.nn.transforms.make_for_sequence_representation
  time_encoding: "delta"
  padding_mask_inp_name: "txn_evt_attr_15_mask"
  events_meta: ${model.embedding.columns_meta}
  bypass: ["epk_id"]

validation_transform:
  _target_: fmlib.nn.transforms.make_for_sequence_representation
  time_encoding: "delta"
  padding_mask_inp_name: "txn_evt_attr_15_mask"
  events_meta: ${model.embedding.columns_meta}
  bypass: ["epk_id"]

autocast:
  _target_: fmlib.training.utils.autocast.make_autocast_wrapper
  do_autocast: False

losses:
  _target_: fmlib.nn.losses.CombinedLoss
  losses:
    body_loss:
      _target_: fmlib.nn.losses.NextKTokensLoss
      hidden_size: ${model.embedding.embedding_dim}
      columns_meta: ${events_meta}
      horizon: 3

metadata:
  epk_id: {}
  event_ids:
    sequential: true
    sequence_length: 128
    padding: 0
  evt_dttm:
    sequential: true
    sequence_length: 128
    padding: 0
  evk_vnv_channel_group:
    sequential: true
    sequence_length: 128
    padding: 0
  evk_vnv_evt_attr_1:
    sequential: true
    sequence_length: 128
    padding: 0
  evk_vnv_sale_product_class_id:
    sequential: true
    sequence_length: 128
    padding: 0
  evk_vnv_sale_type_id:
    sequential: true
    sequence_length: 128
    padding: 0
  holidays_evt_attr_1:
    sequential: true
    sequence_length: 128
    padding: 0
  pos_geo_evt_attr_1:
    sequential: true
    sequence_length: 128
    padding: 0
  txn_evt_attr_4:
    sequential: true
    sequence_length: 128
    padding: 0
  txn_evt_attr_5:
    sequential: true
    sequence_length: 128
    padding: 0
  txn_evt_attr_15:
    sequential: true
    sequence_length: 128
    padding: 0
  txn_evt_attr_9:
    sequential: true
    sequence_length: 128
    padding: 0
  txn_evt_attr_1:
    sequential: true
    sequence_length: 128
    padding: 0
  txn_evt_attr_2:
    sequential: true
    sequence_length: 128
    padding: 0
  txn_evt_attr_3:
    sequential: true
    sequence_length: 128
    padding: 0

training_data:
  _target_: fmlib.data.io.parquet_dataset.ParquetDataset
  source: "/home/datalab/nfs/data/sequence_representation_8M/mini_small"
  metadata: ${metadata}
  partition_size: 131072
  batch_size: 128
  generator:
    _target_: fmlib.utils.generator.make_seeded_generator
    seed: ${seed}

validation_data:
  _target_: fmlib.data.io.parquet_dataset.ParquetDataset
  source: "/home/datalab/nfs/data/sequence_representation_8M/mini_valid"
  metadata: ${metadata}
  partition_size: 131072
  batch_size: 128

epoch_callbacks:
  _target_: fmlib.training.callbacks.epoch.GroupedEpochCallback
  callbacks:
    - _target_: fmlib.training.callbacks.epoch.EarlyStoppingCallback
      metric_to_track: "body_loss_median_rank_0"
      patience: 10
    - _target_: fmlib.training.callbacks.epoch.LoggingEpochCallback
    - _target_: fmlib.training.callbacks.epoch.SaveCheckpointCallback
      base_path: "/home/datalab/nfs/checkpoints/test_body_8m_0"
      metric_to_track: "body_loss_median_rank_0"
      submodule_to_save: "model"
      num_checkpoints: 5
    - _target_: fmlib.training.callbacks.epoch.SaveCheckpointCallback
      base_path: "/home/datalab/nfs/checkpoints/test_body_8m_1"
      metric_to_track: "body_loss_median_rank_0"
      submodule_to_save: "model"
      num_checkpoints: 5

epoch_iterable:
  _target_: fmlib.training.callbacks.epoch.EarlyStoppingIterable
  max_iter: 128
