seed: 42

model:
  _target_: fmlib.nn.models.UpliftFeatureTransformer
  embedding:
    _target_: fmlib.nn.embedding.FeatureEmbedding
    numerical_feature_count: 261
    embedding_dim: 64
    vocab_size: 415
    std_noise: 0.02
  num_encoder_layers: 3
  encoder_block:
    _target_: fmlib.nn.blocks.EncoderBlock
    hidden_dim: ${model.embedding.embedding_dim}
    num_heads: 4
    attn_dropout: 0.15
    dropout: ${model.encoder_block.attn_dropout}
    ffn:
      _target_: fmlib.nn.blocks.STEv2FFN
      model_dim: ${model.embedding.embedding_dim}
      linear_dim: 256  # ${model.embedding.embedding_dim} * 4
      dropout: ${model.encoder_block.attn_dropout}
  aggregation_layer:
    _target_: fmlib.nn.utils.agg.LinearAggregation
    num_features: 315
    embedding_dim: ${model.embedding.embedding_dim}
  # Late fusion option
  late_fusion_layer_norm:
    _target_: torch.nn.LayerNorm
    normalized_shape: 256 # Размерность external hidden_state
  head:
    _target_: fmlib.nn.models.heads.FFNHead
    hidden_dim: 320
    linear_dim: ${model.head.hidden_dim}
    num_classes: 2
    dropout: 0.15
  n_groups: 6

training_step_callbacks:
  _target_: fmlib.training.callbacks.step.GroupedStepCallback
  callbacks:
    - _target_: fmlib.training.callbacks.step.RocAucCallback
      metric_name: "roc_auc_training_treatment"
      target_name: "target_attr_1"
      output_name: "treatment_probs"
    - _target_: fmlib.training.callbacks.step.RocAucCallback
      metric_name: "roc_auc_training_control"
      target_name: "target_attr_1"
      output_name: "control_probs"

validation_step_callbacks:
  _target_: fmlib.training.callbacks.step.GroupedStepCallback
  callbacks:
    - _target_: fmlib.training.callbacks.step.RocAucCallback
      metric_name: "roc_auc_validation_treatment"
      target_name: "target_attr_1"
      output_name: "treatment_probs"
    - _target_: fmlib.training.callbacks.step.RocAucCallback
      metric_name: "roc_auc_validation_control"
      target_name: "target_attr_1"
      output_name: "control_probs"
    - _target_: fmlib.training.callbacks.step.uplift_callback.UpliftCallback
      treatment_output_name: "treatment_probs"
      control_output_name: "control_probs"
      target_name: "target_attr_1"
      group_name: "target_attr_3"
      common_prefix: "validation_"
      ks: [0.01, 0.05, 0.1, 0.25, 0.5]
      classifier_template:
        _target_: sklearn.linear_model.LogisticRegressionCV
        _partial_: True
        random_state: 42
        n_jobs: 8
        cv: 3

evaluation_step_callbacks:
  _target_: fmlib.training.callbacks.step.GroupedStepCallback
  callbacks:
    - _target_: fmlib.training.callbacks.step.RocAucCallback
      metric_name: "roc_auc_evaluation_treatment"
      target_name: "target_attr_1"
      output_name: "treatment_probs"
    - _target_: fmlib.training.callbacks.step.RocAucCallback
      metric_name: "roc_auc_evaluation_control"
      target_name: "target_attr_1"
      output_name: "control_probs"
    - _target_: fmlib.training.callbacks.step.uplift_callback.UpliftCallback
      treatment_output_name: "treatment_probs"
      control_output_name: "control_probs"
      target_name: "target_attr_1"
      group_name: "target_attr_3"
      common_prefix: "evaluation_"
      ks: [0.01, 0.05, 0.1, 0.25, 0.5]
      classifier_template:
        _target_: sklearn.linear_model.LogisticRegressionCV
        _partial_: True
        random_state: 42
        n_jobs: 8
        cv: 3

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001

scheduler:
  _target_: transformers.optimization.get_scheduler
  name: cosine
  num_warmup_steps: 1
  num_training_steps: 300

accelerator:
  _target_: accelerate.Accelerator

training_transform:
  _target_: fmlib.nn.transforms.make_for_uplift_feature_transformer
  bypass: ["epk_id", "target_attr_1", "target_attr_2", "target_attr_3"]
  channel_type: 1

validation_transform:
  _target_: fmlib.nn.transforms.make_for_uplift_feature_transformer
  bypass: ["epk_id", "target_attr_1", "target_attr_2", "target_attr_3"]
  channel_type: 1

evaluation_transform:
  _target_: fmlib.nn.transforms.make_for_uplift_feature_transformer
  bypass: ["epk_id", "target_attr_1", "target_attr_2", "target_attr_3"]
  channel_type: 1

inference_transform:
  _target_: fmlib.nn.transforms.make_for_uplift_feature_transformer
  bypass: ["epk_id", "target_attr_1", "target_attr_2", "target_attr_3"]
  channel_type: 1

autocast:
  _target_: fmlib.training.utils.autocast.make_autocast_wrapper
  do_autocast: False

losses:
  _target_: fmlib.nn.losses.CombinedLoss
  losses:
    tabular_loss:
      _target_: fmlib.nn.losses.uplift_loss.SLearnerLoss
      target_type: 
        _target_: hydra.utils.get_object
        path: torch.float32
      group_name: "target_attr_3"
      target_name: "target_attr_1"
      control_output_name: "control_probs"
      treatment_output_name: "treatment_probs"
      loss_to_wrap:
        _target_: torch.nn.BCELoss

metadata:
  epk_id: {}
  bucket_num: {}
  target_attr_1: {}
  target_attr_2: {}
  target_attr_3: {}
  cat_features:
      sequential: true
      sequence_length: 52
      padding: 0
  num_features:
      sequential: true
      sequence_length: 261
      padding: 0
  seq_hidden_state:
      sequential: true
      sequence_length: 256
      padding: 0

training_data:
  _target_: fmlib.data.io.parquet_dataset.ParquetDataset
  source: "/home/datalab/nfs/data/uplift_feature_transformer/train"
  metadata: ${metadata}
  partition_size: 131072
  batch_size: 2048
  generator:
    _target_: fmlib.utils.generator.make_seeded_generator
    seed: ${seed}

validation_data:
  _target_: fmlib.data.io.parquet_dataset.ParquetDataset
  source: "/home/datalab/nfs/data/uplift_feature_transformer/valid"
  metadata: ${metadata}
  partition_size: 131072
  batch_size: 2048

evaluation_data:
  _target_: fmlib.data.io.parquet_dataset.ParquetDataset
  source: "/home/datalab/nfs/data/uplift_feature_transformer/test"
  metadata: ${metadata}
  partition_size: 131072
  batch_size: 2048

epoch_callbacks:
  _target_: fmlib.training.callbacks.epoch.GroupedEpochCallback
  callbacks:
    - _target_: fmlib.training.callbacks.epoch.EarlyStoppingCallback
      metric_to_track: "validation_calibrated_qini_auc_score"
      patience: 10
    - _target_: fmlib.training.callbacks.epoch.LoggingEpochCallback
    - _target_: fmlib.training.callbacks.epoch.SaveCheckpointCallback
      base_path: "/home/datalab/nfs/checkpoints/test_uplift"
      metric_to_track: "validation_calibrated_uplift_auc_score"
      submodule_to_save: "model"
      num_checkpoints: 5
    - _target_: fmlib.training.callbacks.epoch.SaveCheckpointCallback
      base_path: "/home/datalab/nfs/checkpoints/test_qini"
      metric_to_track: "validation_calibrated_qini_auc_score"
      submodule_to_save: "model"
      num_checkpoints: 5

epoch_iterable:
  _target_: fmlib.training.callbacks.epoch.EarlyStoppingIterable
  max_iter: 128
