weights_path: "model.safetensors"
model:
  _target_: fmlib.nn.models.Trivan
  vocab_size: 5504
  hidden_dim: 512
  positional_encoding_num_buckets: 512
  num_encoder_layers: 6
  num_decoder_layers: 6
  dropout: 0.1
  adapter_ffn:
    _target_: fmlib.nn.blocks.PositionWiseFFN
    model_dim: ${model.hidden_dim}
    linear_dim: 2048
    dropout: ${model.dropout}
  input_encoder_block:
    _target_: fmlib.nn.blocks.EncoderBlock
    hidden_dim: ${model.hidden_dim}
    num_heads: 8
    attn_dropout: ${model.dropout}
    dropout: ${model.dropout}
    ffn: ${model.adapter_ffn}
  encoder_block: ${model.input_encoder_block}
  decoder_block:
    _target_: fmlib.nn.blocks.DecoderBlock
    hidden_dim: ${model.hidden_dim}
    num_heads: 8
    attn_dropout: ${model.dropout}
    dropout: ${model.dropout}
    ffn: ${model.adapter_ffn}
  classification_head:
    _target_: fmlib.nn.models.heads.TrivanClassificationHead
    hidden_dim: ${model.hidden_dim}
    num_classes: 2
  adapter_layer_names:
    - "sm_model"
    - "okko_model"
  output_layer_names:
    - "flower_online_fr_4000_d3"
    - "building_materials_fr_8500_d30"
    - "smm_drugs_fr_4000_d7"
    - "all_building_model_fr_1400_d7"
    - "decorating_materials_fr_4000_d14"
    - "cosmetic_vs_perfume_online_fr_400_d3"
    - "sport_store_fr_4000_d7"
    - "hotels_avia_railways_fr_8500_d30"
    - "fines_fr_500_d7"
    - "bani_fr_3000_d14"
    - "dentist_lab_fr_4000_d14"
    - "ATM_fr_27000_d30"
    - "avia_railways_fr_4000_d7"
    - "bus_fr_1000_d14"
    - "fishing_fr_1400_d14"
    - "taxi_fr_49_d3"
    - "parking_tc_mall_fr_1000_d7"
    - "aeroexpress_fr_100_d14"
    - "restaurants_offline_fr_1400_d7"
    - "scooter_vs_bycicle_fr_10_d3"
    - "profi_education_fr_4000_d14"
    - "full_stack_travel_fr_1400_d14"
    - "foreign_card_fr_2000_d14"
    - "cosmetic_vs_perfume_offline_fr_100_d3"
    - "smm_sleeping_badroom_stuff_fr_1400_d7"
    - "travel_service_fr_27000_d30"
    - "flower_online_fr_1000_to_4000_d7"
    - "travel_service_fr_4000_d7"
    - "smm_smartphone_fr_8500_d30"
    - "foreign_card_fr_2000_d30"
    - "all_building_model_fr_400_d7"
    - "smm_computers_and_gadgets_fr_8500_d14"
    - "video_games_general_fr_1400_d14"
    - "kid_stores_fr_8500_d30"
    - "smm_buy_bicycle_scooter_fr_1500_d30"
    - "universities_fr_4000_d14"
    - "decorating_materials_fr_400_d7"
    - "goods_for_sleep_fr_1400_d7"
    - "psy_fr_1400_d3"
    - "charity_donate_fr_100_d7"
    - "food_online_fr_400_d3"
    - "auto_accessories_fr_4000_d30"
    - "furniture_fr_4000_d14"
    - "citydrive_fr_500_d14_rtb"
    - "beauty_salons_fr_1400_d14"
    - "wedding_date_d90"
    - "jewelry_fr_8500_d30"
    - "all_building_model_fr_27000_d30"
    - "job_search_fr_0_d14"
    - "smm_computers_and_gadgets_fr_8500_d30"
    - "full_stack_culture_fr_4000_d7"
    - "avia_fr_4000_d14"
    - "hotels_fr_27000_d30"
    - "all_medicine_model_fr_8500_d30"
    - "auto_accessories_fr_1400_d14"
    - "hobby_art_sewing_fr_1400_d14"
    - "marketplaces_fr_4000_d14"
    - "smm_computers_and_gadgets_fr_1400_d7"
    - "restaurants_online_fr_1400_d3"
    - "smm_computers_and_gadgets_fr_4000_d7"
    - "smm_household_techn_fr_1400_d7"
    - "full_stack_travel_fr_4000_d7"
    - "furniture_fr_400_d3"
    - "building_materials_fr_4000_d14"
    - "auto_accessories_fr_8500_d14"
    - "goods_for_sleep_fr_8500_d30"
    - "venicle_charge_fr_50_d7"
    - "board_games_fr_1400_d30"
    - "smm_gaming_hardware_fr_4000_d14"
    - "cosmetic_vs_perfume_offline_fr_4000_d14"
    - "smm_cleaning_fr_1400_d7"
    - "avtodor_fr_1000_d30"
    - "fuel_fr_1000_d7"
    - "charity_svo_fr_100_d14"
    - "drugs_fr_4000_d14"
    - "all_travelling_model_fr_8500_d30"
    - "all_electronic_fr_1400_d7"
    - "child_care_fr_1400_d14"
    - "ready_meals_fr_1400_d30"
    - "bus_fr_10_d3"
    - "smm_hygiene_fr_1400_d7"
    - "smm_household_techn_fr_8500_d30"
    - "smm_gaming_hardware_fr_1400_d14"
    - "tires_fr_15000_d14"
    - "all_building_model_fr_27000_d14"
    - "carwash_fr_50_d7"
    - "smm_smartphone_fr_27000_d30"
    - "decorating_materials_fr_1400_d7"
    - "citydrive_fr_0_d7_rtb"
    - "food_offline_fr_1400_d7"
    - "dating_fr_200_d14"
    - "smm_gaming_fr_1400_d30"
    - "all_travelling_model_fr_4000_d14"
    - "dating_fr_200_d3"
    - "universities_fr_1400_d14"
    - "avia_railways_fr_1400_d7"
    - "restaurants_offline_fr_1400_d3"
    - "avia_fr_8500_d30"
    - "all_medicine_model_fr_4000_d7"
    - "smm_cleaning_fr_1400_d14"
    - "pet_shops_fr_4000_d14"
    - "auto_accessories_fr_4000_d14"
    - "drugs_fr_400_d3"
    - "all_electronic_fr_4000_d7"
    - "food_offline_fr_400_d3"
    - "sport_store_fr_1400_d7"
    - "all_building_model_fr_4000_d14"
    - "scooter_rent_fr_10_d7"
    - "dating_fr_200_d7"
    - "smm_sleeping_badroom_stuff_fr_27000_d30"
    - "repairing_auto_fr_4000_to_1000000_d14"
    - "all_electronic_fr_4000_d14"
    - "pet_shops_fr_1400_d14"
    - "food_online_fr_1400_d14"
    - "ZKH_fr_1400_d14"
    - "otello_fr_1400_d30"
    - "furniture_fr_400_d7"
    - "full_stack_building_fr_400_d3"
    - "all_culture_events_model_fr_1400_d7"
    - "smm_household_goods_fr_4000_d14"
    - "auto_accessories_fr_8500_d30"
    - "smm_household_goods_fr_1400_d7"
    - "flower_offline_fr_4000_d7"
    - "kid_stores_fr_8500_d14"
    - "sberboom_activate_d14"
    - "hotels_avia_railways_fr_1400_d14"
    - "cinemas_fr_400_d3"
    - "cinemas_fr_400_d7"
    - "psy_fr_1400_d7"
    - "car_rent_fr_200_d7"
    - "dentist_lab_fr_4000_d7"
    - "smm_sleeping_badroom_stuff_fr_8500_d30"
    - "auto_accessories_fr_1400_d7"
    - "goods_for_sleep_fr_1400_d14"
    - "travel_service_fr_8500_d14"
    - "sport_store_fr_1400_d14"
    - "smm_smartphone_fr_27000_d14"
    - "pet_care_fr_1400_d7"
    - "parking_city_fr_250_d7"
    - "smm_drugs_fr_400_d3"
    - "marketplaces_fr_400_d3"
    - "pet_shops_fr_400_d3"
    - "kid_stores_fr_4000_d14"
    - "all_travelling_model_fr_27000_d14"
    - "jewelry_fr_4000_d14"
    - "school_education_fr_1400_d14"
    - "smm_sleeping_badroom_stuff_fr_400_d7"
    - "flower_offline_fr_4000_d14"
    - "all_building_model_fr_4000_d7"
    - "all_travelling_model_fr_1400_d14"
    - "household_goods_fr_1400_d14"
    - "repairing_auto_fr_27000_d30"
    - "shoes_fr_400_d7"
    - "fuel_fr_200_d3"
    - "smm_hygiene_fr_1400_d14"
    - "skills_fr_27000_d30"
    - "subscription_fr_49_d3"
    - "railway_fr_8500_d30"
    - "fuel_fr_1000_d14"
    - "pet_shops_fr_400_d7"
    - "hotels_avia_railways_fr_27000_d14"
    - "smm_hygiene_fr_100_d3"
    - "subscription_music_fr_49_d3"
    - "shoes_fr_4000_d14"
    - "shoes_fr_8500_d30"
    - "hotels_fr_8500_d30"
    - "household_goods_fr_100_d3"
    - "ready_meals_fr_1400_d14"
    - "parking_tc_mall_fr_250_to_500_d3"
    - "railway_fr_4000_d14"
    - "shoes_fr_4000_d30"
    - "medical_merchant_labs_fr_8500_d30"
    - "tires_fr_15000_d30"
    - "full_stack_travel_fr_8500_d14"
    - "ZKH_fr_4000_d14"
    - "repairing_auto_fr_4000_d7"
    - "avia_railways_fr_1400_d14"
    - "subscription_fr_200_d3"
    - "full_stack_culture_fr_4000_d14"
    - "full_stack_travel_fr_8500_d30"
    - "all_travelling_model_fr_4000_d7"
    - "video_games_general_fr_700_d7"
    - "bus_fr_10_d7"
    - "citydrive_fr_500_d7_ftb"
    - "subscription_fr_49_d14"
    - "suburban_transport_fr_1000_d14"
    - "smm_buy_bicycle_scooter_fr_4000_d14"
    - "board_games_fr_400_d7"
    - "full_stack_building_fr_27000_d30"
    - "shoes_fr_8500_d14"
    - "video_games_social_network_fr_50_d7"
    - "restaurants_offline_fr_4000_d7"
    - "food_delivery_fr_4000_d7"
    - "taxi_fr_400_d3"
    - "flower_online_fr_4000_d7"
    - "citydrive_fr_500_d7_rtb"
    - "cosmetic_vs_perfume_online_fr_4000_d7"
    - "hotels_fr_27000_d14"
    - "bicycle_fr_2000_d7"
    - "avtodor_fr_0_d14"
    - "cosmetic_vs_perfume_online_fr_100_d3"
    - "suburban_transport_fr_10_d7"
    - "avia_railways_fr_8500_d14"
    - "repairing_auto_fr_400_d3"
    - "skills_fr_8500_d30"
    - "pet_shops_fr_8500_d30"
    - "hotels_fr_1400_d7"
    - "beauty_salons_fr_8500_d14"
    - "travel_service_fr_1400_d7"
    - "gym_fr_27000_d30"
    - "furniture_fr_1400_d7"
    - "goods_for_sleep_fr_4000_d14"
    - "full_stack_culture_fr_1400_d14"
    - "decorating_materials_fr_8500_d14"
    - "dentist_lab_fr_7000_d30"
    - "medical_merchant_labs_fr_1400_d14"
    - "language_education_fr_4000_d14"
    - "travel_service_fr_8500_d30"
    - "subscription_movies_fr_49_d3"
    - "smm_buy_bicycle_scooter_fr_1500_d14"
    - "all_medicine_model_fr_8500_d14"
    - "parking_tc_mall_fr_500_to_1000_d7"
    - "sport_store_fr_400_d7"
    - "gym_fr_8500_d14"
    - "gym_fr_4000_d7"
    - "car_rent_fr_1000_d7"
    - "household_goods_fr_4000_d14"
    - "all_electronic_fr_8500_d30"
    - "cosmetic_vs_perfume_offline_fr_400_d3"
    - "medical_merchant_labs_fr_4000_d14"
    - "smm_computers_and_gadgets_fr_4000_d14"
    - "skills_fr_8500_d14"
    - "theaters_fr_1400_d14"
    - "book_shops_fr_400_d7"
    - "pet_care_fr_1400_d14"
    - "avia_fr_27000_d30"
    - "ns_cg"
    - "language_education_fr_1400_d14"
    - "flower_offline_fr_1000_to_4000_d7"
    - "book_shops_fr_1400_d14"
    - "repairing_auto_fr_1200_to_1000000_d7"
    - "restaurants_offline_fr_400_d3"
    - "bicycle_fr_2000_d30"
    - "car_rent_fr_1000_d14"
    - "hotels_fr_4000_d7"
    - "hotels_fr_8500_d14"
    - "repairing_auto_fr_400_to_1000000_d3"
    - "avia_fr_27000_d14"
    - "marketplaces_fr_8500_d14"
    - "food_offline_fr_1400_d14"
    - "skills_fr_4000_d7"
    - "hotels_avia_railways_fr_1400_d7"
    - "all_building_model_fr_8500_d30"
    - "full_stack_travel_fr_4000_d14"
    - "repairing_auto_fr_1200_d7"
    - "hotels_fr_4000_d14"
    - "scooter_rent_fr_10_d3"
    - "cosmetic_vs_perfume_online_fr_1400_d7"
    - "school_education_fr_8500_d30"
    - "shoes_fr_1400_d14"
    - "suburban_transport_fr_10_d3"
    - "citydrive_fr_0_d7_ftb"
    - "parking_tc_mall_fr_1000_d3"
    - "full_stack_travel_fr_27000_d30"
    - "parking_tc_mall_fr_250_d3"
    - "car_rent_fr_200_d3"
    - "smm_smartphone_fr_50000_d14"
    - "beauty_salons_fr_4000_d7"
    - "book_shops_fr_1400_d7"
    - "avia_railways_fr_4000_d14"
    - "algoritmika_buy_d14"
    - "smm_household_techn_fr_8500_d14"
    - "hotels_avia_railways_fr_8500_d14"
    - "household_goods_fr_1400_d7"
    - "flower_online_fr_1000_to_4000_d3"
    - "charity_general_fr_100_d14"
    - "avia_fr_8500_d14"
    - "food_offline_fr_1400_d3"
    - "restaurants_online_fr_400_d3"
    - "kid_stores_fr_4000_d7"
    - "avia_railways_fr_27000_d30"
    - "repairing_auto_fr_4000_d14"
    - "theaters_fr_1400_d7"
    - "baby_education_fr_1400_d14"
    - "all_culture_events_model_fr_4000_d14"
    - "veterinary_fr_1400_d14"
    - "hotels_avia_railways_fr_27000_d30"
    - "smm_gaming_accessory_fr_1400_d7"
    - "subscription_books_fr_49_d3"
    - "fines_fr_2000_d7"
    - "avtodor_fr_0_d7"
    - "theaters_fr_400_d14"
    - "stoloto_fr_50_d14"
    - "building_materials_fr_4000_d7"
    - "all_building_model_fr_400_d3"
    - "food_online_fr_4000_d14"
    - "board_games_fr_1000_d7"
    - "parking_city_fr_1000_d7"
    - "decorating_materials_fr_1400_d14"
    - "flower_offline_fr_1000_to_4000_d14"
    - "video_games_general_fr_700_d14"
    - "kid_stores_fr_1400_d7"
    - "tires_fr_2000_d7"
    - "all_travelling_model_fr_1400_d7"
    - "taxi_fr_49_d7"
    - "decorating_materials_fr_8500_d30"
    - "child_care_fr_4000_d7"
    - "furniture_fr_27000_d30"
    - "smm_household_techn_fr_27000_d30"
    - "building_materials_fr_1400_d14"
    - "railway_fr_1400_d14"
    - "book_shops_fr_400_d3"
    - "repairing_auto_fr_8500_d14"
    - "universities_fr_1400_d7"
    - "venicle_charge_fr_50_d3"
    - "beauty_salons_fr_1400_d7"
    - "parking_tc_mall_fr_250_d7"
    - "baby_education_fr_1400_d7"
    - "restaurants_offline_fr_4000_d14"
    - "school_education_fr_1400_d7"
    - "parking_city_fr_250_to_500_d3"
    - "marketplaces_fr_1400_d3"
    - "smm_hygiene_fr_400_d3"
    - "aeroexpress_fr_100_d7"
    - "book_shops_fr_400_d14"
    - "repairing_auto_fr_8500_d30"
    - "smm_computers_and_gadgets_fr_1400_d14"
    - "hotels_avia_railways_fr_4000_d7"
    - "edu_other_hobby_fr_1400_d14"
    - "all_culture_events_model_fr_400_d3"
    - "bani_fr_3000_d30"
    - "cosmetic_vs_perfume_offline_fr_4000_d7"
    - "all_travelling_model_fr_8500_d14"
    - "all_medicine_model_fr_4000_d14"
    - "kid_stores_fr_27000_d30"
    - "school_education_fr_0_d3"
    - "railway_fr_8500_d14"
    - "furniture_fr_8500_d14"
    - "museum_art_fr_400_d7"
    - "fishing_fr_400_d7"
    - "travel_service_fr_27000_d14"
    - "wedding_salon_fr_2000_d14"
    - "food_online_fr_1400_d7"
    - "railway_fr_1400_d7"
    - "video_games_social_network_fr_50_d14"
    - "clothes_fr_1400_d14"
    - "approved_auto_credit_d30"
    - "profi_education_fr_27000_d30"
    - "full_stack_building_fr_4000_d14"
    - "edu_other_hobby_fr_4000_d30"
    - "ZKH_fr_1400_d7"
    - "driving_school_fr_1000_d14"
    - "repairing_auto_fr_8500_to_1000000_d30"
    - "kid_stores_fr_1400_d14"
    - "avtodor_fr_0_d30"
    - "wedding_salon_fr_2000_d30"
    - "spa_fr_4000_d7"
    - "smm_household_techn_fr_4000_d14"
    - "full_stack_travel_fr_1400_d7"
    - "food_delivery_fr_1400_d7"
    - "smm_computers_and_gadgets_fr_27000_d14"
    - "restaurants_online_fr_4000_d7"
    - "full_stack_building_fr_1400_d7"
    - "pet_shops_fr_1400_d7"
    - "carwash_fr_0_d3"
    - "decorating_materials_fr_27000_d30"
    - "smm_household_goods_fr_400_d7"
    - "smm_gaming_accessory_fr_1400_d14"
    - "skills_fr_4000_d14"
    - "repairing_auto_fr_4000_to_1000000_d7"
    - "driving_school_fr_1000_d7"
    - "hobby_art_sewing_fr_600_d7"
    - "taxi_fr_1400_d14"
    - "tips_fr_0_to_1000_d7"
    - "flower_online_fr_1000_to_4000_d14"
    - "ZKH_fr_49_d3"
    - "building_materials_fr_400_d3"
    - "baby_education_fr_400_d7"
    - "clothes_fr_4000_d14"
    - "charity_svo_fr_100_d7"
    - "full_stack_building_fr_8500_d14"
    - "wedding_date_d30"
    - "language_education_fr_8500_d30"
    - "full_stack_building_fr_4000_d7"
    - "spa_fr_4000_d14"
    - "marketplaces_fr_1400_d7"
    - "gym_fr_1400_d14"
    - "sport_store_fr_8500_d14"
    - "ready_meals_fr_1400_d3"
    - "subscription_fr_1400_d7"
    - "smm_hygiene_fr_400_d7"
    - "building_materials_fr_1400_d7"
    - "pet_care_fr_4000_d14"
    - "gym_fr_4000_d14"
    - "railway_fr_27000_d30"
    - "ready_meals_fr_1400_d7"
    - "gym_fr_1400_d7"
    - "full_stack_culture_fr_1400_d7"
    - "parking_tc_mall_fr_250_to_500_d7"
    - "smm_drugs_fr_1400_d14"
    - "veterinary_fr_1400_d7"
    - "edu_other_hobby_fr_400_d7"
    - "edu_other_hobby_fr_4000_d14"
    - "fines_fr_15000_d30"
    - "building_materials_fr_8500_d14"
    - "fines_fr_15000_d14"
    - "edu_other_hobby_fr_1400_d7"
    - "cosmetic_vs_perfume_online_fr_1400_d14"
    - "citydrive_fr_500_d14_ftb"
    - "furniture_fr_8500_d30"
    - "smm_smartphone_fr_50000_d30"
    - "food_online_fr_1400_d3"
    - "clothes_fr_4000_d30"
    - "clothes_fr_400_d7"
    - "smm_sleeping_badroom_stuff_fr_1400_d14"
    - "child_care_fr_1400_d7"
    - "smm_drugs_fr_100_d3"
    - "tires_fr_4000_d14"
    - "food_online_fr_4000_d7"
    - "all_medicine_model_fr_27000_d30"
    - "ZKH_fr_4000_d7"
    - "charity_donate_fr_100_d14"
    - "universities_fr_8500_d30"
    - "kid_stores_fr_400_d3"
    - "gym_fr_8500_d30"
    - "smm_household_goods_fr_100_d3"
    - "language_education_fr_1400_d7"
    - "cinemas_fr_400_d14"
    - "smm_drugs_fr_1400_d7"
    - "board_games_fr_1000_d14"
    - "parking_tc_mall_fr_500_to_1000_d3"
    - "smm_gaming_fr_1400_d14"
    - "all_electronic_fr_27000_d14"
    - "taxi_fr_1400_d7"
    - "avia_railways_fr_27000_d14"
    - "drugs_fr_1400_d14"
    - "cosmetic_vs_perfume_online_fr_4000_d14"
    - "avia_railways_fr_8500_d30"
    - "stoloto_fr_50_d7"
    - "theaters_fr_4000_d14"
    - "travel_service_fr_1400_d14"
    - "video_games_general_fr_50_d7"
    - "smm_drugs_fr_4000_d14"
    - "spa_fr_1400_d7"
    - "charity_general_fr_100_d7"
    - "smm_sleeping_badroom_stuff_fr_4000_d14"
    - "carwash_fr_50_d14"
    - "fines_fr_500_d3"
    - "tires_fr_2000_d14"
    - "smm_computers_and_gadgets_fr_27000_d30"
    - "clothes_fr_8500_d14"
    - "avtodor_fr_1000_d7"
    - "mealty_fr_100_d7"
    - "board_games_fr_1400_d14"
    - "decorating_materials_fr_400_d3"
    - "gym_fr_400_d3"
    - "mealty_fr_100_d3"
    - "travel_service_fr_4000_d14"
    - "building_materials_fr_400_d7"
    - "parking_city_fr_250_d3"
    - "ZKH_fr_400_d3"
    - "hobby_art_sewing_fr_600_d30"
    - "car_rent_fr_1000_d3"
    - "smm_cleaning_fr_400_d3"
    - "drugs_fr_1400_d7"
    - "smm_gaming_accessory_fr_4000_d30"
    - "smm_household_techn_fr_1400_d14"
    - "flower_offline_fr_1000_to_4000_d3"
    - "profi_education_fr_4000_d7"
    - "veterinary_fr_4000_d7"
    - "all_travelling_model_fr_27000_d30"
    - "full_stack_travel_fr_27000_d14"
    - "household_goods_fr_400_d7"
    - "jewelry_fr_4000_d7"
    - "smm_gaming_accessory_fr_4000_d14"
    - "sport_store_fr_8500_d30"
    - "restaurants_online_fr_4000_d14"
    - "smm_smartphone_fr_8500_d14"
    - "pk_tg"
    - "repairing_auto_fr_8500_to_1000000_d14"
    - "ATM_fr_100_d3"
    - "hotels_fr_1400_d14"
    - "all_electronic_fr_27000_d30"
    - "smm_gaming_hardware_fr_8500_d30"
    - "aeroexpress_fr_100_d30"
    - "mm_cg"
    - "mealty_fr_100_d14"
    - "hobby_art_sewing_fr_1400_d30"
    - "pk_cg"
    - "flower_offline_fr_4000_d3"
    - "veterinary_fr_4000_d14"
    - "restaurants_online_fr_1400_d7"
    - "bicycle_fr_2000_d14"
    - "job_search_fr_0_d30"
    - "parking_city_fr_500_to_1000_d7"
    - "smm_cleaning_fr_400_d7"
    - "full_stack_building_fr_1400_d14"
    - "food_offline_fr_4000_d14"
    - "ATM_fr_5000_d14"
    - "all_culture_events_model_fr_4000_d7"
    - "smm_gaming_hardware_fr_27000_d30"
    - "bani_fr_3000_d7"
    - "smm_cleaning_fr_100_d3"
    - "wedding_salon_fr_8500_d30"
    - "dentist_lab_fr_7000_d14"
    - "parking_city_fr_1000_d3"
    - "sport_store_fr_4000_d14"
    - "dentist_lab_fr_27000_d30"
    - "parking_city_fr_500_to_1000_d3"
    - "all_electronic_fr_8500_d14"
    - "hotels_avia_railways_fr_4000_d14"
    - "theaters_fr_400_d7"
    - "food_delivery_fr_400_d3"
    - "all_building_model_fr_1400_d14"
    - "child_care_fr_400_d3"
    - "kk_tg"
    - "mm_tg"
    - "furniture_fr_1400_d14"
    - "railway_fr_27000_d14"
    - "beauty_salons_fr_8500_d30"
    - "profi_education_fr_8500_d30"
    - "netology_buy_d14"
    - "avia_fr_4000_d7"
    - "building_materials_fr_27000_d30"
    - "spa_fr_1400_d14"
    - "parking_city_fr_250_to_500_d7"
    - "food_delivery_fr_1400_d3"
    - "all_building_model_fr_8500_d14"
    - "medical_merchant_labs_fr_400_d3"
    - "auto_credit_request_d30"
    - "full_stack_building_fr_8500_d30"
    - "all_culture_events_model_fr_1400_d14"
    - "medical_merchant_labs_fr_1400_d7"
    - "subscription_fr_1400_d14"
    - "ns_tg"
    - "railway_fr_4000_d7"
    - "cosmetic_vs_perfume_offline_fr_1400_d14"
    - "kid_stores_fr_400_d7"
    - "veterinary_fr_400_d3"
    - "profi_education_fr_0_d3"
    - "avtodor_fr_1000_d14"
    - "fines_fr_2000_d14"
    - "all_electronic_fr_1400_d14"
    - "wedding_date_d60"
    - "beauty_salons_fr_4000_d14"
    - "clothes_fr_8500_d30"
    - "smm_buy_bicycle_scooter_fr_4000_d30"
    - "child_care_fr_4000_d14"
    - "carwash_fr_0_d7"
    - "cosmetic_vs_perfume_offline_fr_1400_d7"
    - "kk_cg"
    - "hobby_art_sewing_fr_600_d14"
    - "full_stack_culture_fr_400_d3"
    - "all_medicine_model_fr_400_d3"
    - "jewelry_fr_27000_d30"
    - "ATM_fr_100_to_5000_d3"
    - "suburban_transport_fr_1000_d7"
    - "flower_online_fr_4000_d14"
    - "museum_art_fr_400_d14"
    - "repairing_auto_fr_27000_to_1000000_d30"
    - "ATM_fr_5000_d7"
    - "food_offline_fr_4000_d7"
    - "ATM_fr_27000_d14"
    - "smm_household_goods_fr_1400_d14"